### ISSUE TITLE
Improve sound feedback when typing

### ISSUE THREAD

**Issue by duff92** [AxessLab/typing#59]
- [ ] Improve latency for sounds either by speed or shorten the clips

Suggested solutions
- [x] Implement cache solution
- [x] Change configs when calling
- [x] Call directly to Google

Important to not spend too much time on each but find one of them working.

**Comment by arethsu** [comment]
Current TTS solution has a latency of about 200-300 ms. The [new attempt](https://github.com/AxessLab/typing-audio-server/pull/1) has a slightly lower latency of 100-200 ms for new requests (tested from a fiber connection). Cached requests can go as low as 35 ms.

**Comment by arethsu** [comment]
As mentioned in [the PR for the new TTS server](https://github.com/AxessLab/typing-audio-server/pull/1), I suggested that assets were to be uploaded to cloud object storage. I tested Amazon AWS S3 for this, since they recently opened up a datacenter in Stockholm.

Latency to the `eu-north-1` datacenter (Stockholm) is about 15-40 ms. I suggest we create a bucket and store the assets there. ~^w^~
